### ISSUE TITLE
Connection Error

### ISSUE THREAD

**Issue by Sempiternity87** [tulleuchen/jirastopwatch#140]
Received an error when attempting to connect with API token.

"Jira StopWatch could not connect to your Jira server. Error returned:

An error occurred while parsing EntityName. Line 26, position 26."

**Comment by Sempiternity87** [comment]
Possibly this only works with the Hosted Jira? We use our own server to host Jira.

[jirastopwatch.log](https://github.com/carstengehling/jirastopwatch/files/3149154/jirastopwatch.log)

**Comment by DavidHansen-0x454d43** [comment]
I'm seeing this same error, and we have a self-managed instance as well.

Does anyone know how to generate a token for self-managed installs?
Or how to go back to logging in with a password?

**Comment by tulleuchen** [comment]
You don't need a token for self managed installs. I've just taken over the project. But I know you can definitely use this on the server version I'm using it on a server version that I've setup. I can take a look at the errors here and see if I can give you some direction.

**Comment by tulleuchen** [comment]
Please see this thread for details https://github.com/tulleuchen/jirastopwatch/issues/147
