### ISSUE TITLE
Allow the modification of the time record before submitting

### ISSUE THREAD

**Issue by jonathan-niven** [tulleuchen/jirastopwatch#143]
It's pretty easy to not hit the start button, and realising an hour later that you haven't. I propose to add a feature found in the [Toggle time tracking app](https://toggl.com), where a user has the ability to modify the time record (e.g. changing the start time and have the timer update to the actual amount of work). 
Of course this would only be possible before submitting the record.

**Comment by carstengehling** [comment]
It's already available. If you double-click on the time-field, you have the ability to modify the time.
