### ISSUE TITLE
Keyboard shortcut support

### ISSUE THREAD

**Issue by jonathan-niven** [tulleuchen/jirastopwatch#144]
Adding the ability to assign keyboard shortcuts to common actions would be very useful.
Some examples of common actions:

- Bring up the timer/hide the timer. This shortcut should bring the timer to the foreground and apply window focus to it. It serves as the starting point for any other shortcuts and therefore should work even when the window is not in focus.
- Start/stop timers (Perhaps with a number to select which). These shortcuts should only work from within the timer, meaning they can be bound to other things in different applications.
- Create new timer. This should add a new timer and focus the text box, allowing a user to type without moving from the keyboard.

The overall purpose of these shortcuts is to allow mouseless time entry, further reducing the cognitive load and barrier to entry for time tracking.

**Comment by tulleuchen** [comment]
There are already keyboard shortcuts. 
https://jirastopwatch.com/doc/#keyboard

To create a keyboard shortcut to the application, or any application (in Windows) you create a shortcut to the executable, in this case StopWatch.exe. 
The right click on the shortcut and click properties
Click on the Shortcut tab and you can create a keyboard shortcut there. 

It would look something like this and these kinds of application shortcuts will be specific to your system. 

![image](https://user-images.githubusercontent.com/45860725/94641532-20527180-02a7-11eb-85f5-4ba19be53a21.png)
