### ISSUE TITLE
Unhandled error ocurred

### ISSUE THREAD

**Issue by cristiancarraro** [tulleuchen/jirastopwatch#151]
When I start it, shows the following error:

![2020-04-27 10_56_31-Window](https://user-images.githubusercontent.com/10561034/80380318-ca9c1800-8875-11ea-9c1d-2a1fd463367e.png)

LOG:
27/04/2020 9:18:57: Unhandled UI Exception
27/04/2020 9:18:57: DPAPI was unable to decrypt data.
27/04/2020 9:18:57:    en StopWatch.DPAPI.Decrypt(Byte[] cipherTextBytes, Byte[] entropyBytes, String& description)
   en StopWatch.DPAPI.Decrypt(String cipherText, String entropy, String& description)
   en StopWatch.Settings.ReadSettings()
   en StopWatch.Settings.Load()
   en StopWatch.MainForm..ctor()
   en StopWatch.Program.Main()

any ideas?
Regards

**Comment by carstengehling** [comment]
Just delete the config file sonewhere in %APPDATA% and start again.

**Comment by cristiancarraro** [comment]
Thankyou!!!
its working!!!
