### ISSUE TITLE
Add Username/Password for Authentication

### ISSUE THREAD

**Issue by Mikerad1** [tulleuchen/jirastopwatch#154]
I use Jira on a self hosted server and there doesnt seem like there is functionality to login with an API token. so can you make it optional?

**Comment by creativewild** [comment]
I second this, it would be very very useful on self-hosted.

**Comment by invi2000** [comment]
See:
https://github.com/tulleuchen/jirastopwatch/issues/147

**Comment by tulleuchen** [comment]
This is already working 
Please take a look at the comments in https://github.com/tulleuchen/jirastopwatch/issues/147
